Fix compilation issue with Python 3.11.
Compilation is currently failing with the error:
File "Documentation/conf.py", line 61, in <module>
    with open(filename, 'rU') as f:
         ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

The Porting to Python 3.11 guide [0] says:
open(), io.open(), codecs.open() and fileinput.FileInput no longer
accept 'U' ("universal newline") in the file mode. In Python 3,
"universal newline" mode is used by default whenever a file is
opened in text mode, and the 'U' flag has been deprecated since
Python 3.3.

0: https://docs.python.org/3.11/whatsnew/3.11.html#porting-to-python-3-11

Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
(cherry picked from commit a810bd80f572eefb2c14096a1413a45d7673314d)